###########################################################
### Welcome to Beautiful Jekyll!
### This config file is meant for settings that affect your entire website. When you first
### set up your website you should go through all these settings and edit them, but after
### the initial set up you won't need to come back to this file often.
###########################################################

############################
# --- Required options --- #
############################

# Name of website
title: Hebatalla Elgamal

description: Senior Data Analyst | Power BI | Python | SQL | Supply Chain Analytics | MIT SCM

# Your name to show in the footer
author: Heba

# --- Navigation Bar --- #

# List of links in the navigation bar
navbar-links:
  About Me: "aboutme"
  Experience: "experience"
  Projects: "projects"
  Skills: "skills"
  Education: "education"
  Contact: "contact"

# --- Background Images --- #

# Image to show in the navigation bar
avatar: "/assets/img/Heba-Profile.jpg"

# By default, the navbar is light. You can change it to dark
navbar-col: "#1a1a2e"
navbar-text-col: "#ffffff"
navbar-border-col: "#16213e"

# --- Footer Social Media Links --- #

social-network-links:
  email: "heba.adel.elgamal@gmail.com"
  linkedin: www.linkedin.com/in/heba-adel-b582a0103
  github: HebaAdel892

# --- General Website Settings --- #

# Select your timezone
timezone: "Asia/Riyadh"

# Select your markdown engine
markdown: kramdown

# Prettify the URLs
permalink: /:year-:month-:day-:title/

# --- Don't Edit Below This Line (Unless You Know What You're Doing) --- #

url: ""

excerpt_length: 50

highlighter: rouge

kramdown:
  input: GFM

plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 5

exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/
